name: Sync Github Prs to Notion
on:
    issues:
        types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
    pull_request:
        types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]
    
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
        - name: Sync Github PRs to Notion
          uses: sivashanmukh/github-notion-pr-sync@1.0.0
          with:
            notionKey: secret_Ay6d3KrOh3YVVxaoAAUFnMdqvVkgTH2vEEtqDpyNmsV
            notionDatabaseId: d97a6e633ddd42a99be1714513e82d35
            githubKey: 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
