name: Sync Github Prs to Notion
on:
    issues:
        types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
    pull_request:
        types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]
    
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
        - name: Sync Github PRs to Notion
          uses: sivashanmukh/github-notion-pr-sync@1.0.0
          with:
            notionKey: secret_hlVxtHx2rDxbK4rN5qyeUrMkcB1ubjgG3QEgvA5ZgD4
            notionDatabaseId: ffd57ae59c8e449e95767f99ab438b3c
            githubKey: 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
